name = "ThermalKineticjl"
uuid = "3094f75b-e9c7-4503-ac40-277ea4add310"
version = "1.0.0-DEV"
authors = ["Kirill Klemazov <klemazov_kirill@mail.ru> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
DifferentialEquations = "7.17.0"
Optim = "2.0.0"
Plots = "1.41.4"
Pluto = "0.20.21"
PlutoUI = "0.7.79"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
