name = "ThermalKineticjl"
uuid = "3094f75b-e9c7-4503-ac40-277ea4add310"
authors = ["Kirill Klemazov <klemazov_kirill@mail.ru> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
